//
// Created by Gegel85 on 27/04/2022.
//

#ifndef SOFGV_PROTOCOL_HPP
#define SOFGV_PROTOCOL_HPP


namespace SpiralOfFate
{
	enum Opcode {
		OPCODE_HELLO,
		OPCODE_OLLEH,
		OPCODE_REDIRECT,
		OPCODE_PING,
		OPCODE_PONG,
		OPCODE_GAME_FRAME,
		OPCODE_INIT_REQUEST,
		OPCODE_INIT_SUCCESS,
		OPCODE_INIT_ERROR,
		OPCODE_DELAY_UPDATE,
		OPCODE_MENU_SWITCH,
		OPCODE_SYNC_TEST,
		OPCODE_STATE,
		OPCODE_QUIT,
	};
}


#endif //SOFGV_PROTOCOL_HPP
